SELECT DISTINCT J.NOME, J.DATA_NASC, T.NOME, P.DATA, P.LOCAL, JO.CLASSICO
FROM JOGADOR J JOIN TIME T
ON J.TIME = T.NOME
JOIN JOGA JO
ON JO.TIME1 = T.NOME OR JO.TIME2 = T.NOME
JOIN PARTIDA P
ON JO.TIME1 = P.TIME1 AND JO.TIME2 = P.TIME2
ORDER BY J.NOME DESC, P.DATA DESC;