CREATE TABLE TIME (
    NOME VARCHAR2(30) NOT NULL,
    ESTADO CHAR(2),
    TIPO VARCHAR2(30),
    SALDO_GOLS NUMBER,
    
    CONSTRAINT PK_TIME PRIMARY KEY(NOME)
);

CREATE TABLE JOGA (
    TIME1 VARCHAR2(30) NOT NULL,
    TIME2 VARCHAR2(30) NOT NULL,
    CLASSICO CHAR(1) DEFAULT 'N',
    
    CONSTRAINT CHECK_CLASSICO CHECK(CLASSICO IN ('S','N')),
    CONSTRAINT PK_JOGA PRIMARY KEY(TIME1, TIME2),
    CONSTRAINT FK1_JOGA FOREIGN KEY(TIME1) REFERENCES TIME(NOME) ON DELETE CASCADE,
    CONSTRAINT FK2_JOGA FOREIGN KEY(TIME2) REFERENCES TIME(NOME) ON DELETE CASCADE
);

CREATE TABLE PARTIDA (
    TIME1 VARCHAR2(30) NOT NULL,
    TIME2 VARCHAR(30) NOT NULL,
    DATA DATE NOT NULL,
    PLACAR VARCHAR(8),
    LOCAL VARCHAR2(50),
    
    CONSTRAINT CHECK_PLACAR CHECK(REGEXP_LIKE(PLACAR, '^\d{1,2}x\d{1,2}$')),
    CONSTRAINT PK_PARTIDA PRIMARY KEY(TIME1, TIME2, DATA),
    CONSTRAINT FK1_PARTIDA FOREIGN KEY(TIME1, TIME2) REFERENCES JOGA(TIME1, TIME2) ON DELETE CASCADE
);

CREATE TABLE JOGADOR (
    CPF CHAR(14) NOT NULL,
    RG CHAR(14) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    DATA_NASC DATE NOT NULL,
    NATURALIDADE VARCHAR2(20),
    TIME VARCHAR2(30),
    
    CONSTRAINT PK_JOGADOR PRIMARY KEY(CPF),
    CONSTRAINT SK_JOGADOR UNIQUE(RG, NOME),
    CONSTRAINT FK_JOGADOR FOREIGN KEY(TIME) REFERENCES TIME(NOME) ON DELETE SET NULL
    
);

CREATE TABLE POSICAO_JOGADOR(
    JOGADOR CHAR(14) NOT NULL,
    POSICAO VARCHAR2(20) NOT NULL,
    
    CONSTRAINT PK_POSICAO_JOGADOR PRIMARY KEY(JOGADOR, POSICAO),
    CONSTRAINT FK_POSICAO_JOGADOR FOREIGN KEY(JOGADOR) REFERENCES JOGADOR(CPF) ON DELETE CASCADE
    
);

CREATE TABLE DIRETOR(
    TIME VARCHAR2(30) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    
    CONSTRAINT PK_DIRETOR PRIMARY KEY(TIME, NOME),
    CONSTRAINT FK_DIRETOR FOREIGN KEY(TIME) REFERENCES TIME(NOME) ON DELETE CASCADE

);

CREATE TABLE UNIFORME (
    TIME VARCHAR2(30) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL,
    COR_PRINCIPAL VARCHAR2(10) NOT NULL,
    
    CONSTRAINT PK_UNIFORME PRIMARY KEY(TIME, TIPO),
    CONSTRAINT FK_UNIFORME FOREIGN KEY(TIME) REFERENCES TIME(NOME) ON DELETE CASCADE
    
);