CREATE TABLE ALUNO (

    NUSP NUMBER(8) NOT NULL,
    CPF CHAR(14),
    RG CHAR(14),
    UF CHAR(2),
    NOME VARCHAR(50) NOT NULL,
    DATANASC DATE NOT NULL,
    
    CONSTRAINT PK_NUSP PRIMARY KEY(NUSP),
    CONSTRAINT SK_CPF UNIQUE(CPF),
    CONSTRAINT TK_CPF_RG UNIQUE(RG, UF),

);

CREATE TABLE PROFESSOR (

		NFUNC NUMBER NOT NULL,
		NOME VARCHAR2(30) NOT NULL,
		TITULACAO CHAR(7) NOT NULL,
		
		CONSTRAINT PK_PROFESSOR PRIMARY KEY(NFUNC)
		CONSTRAINT CHECK_TITULACAO CHECK (UPPER(TITULACAO) IN ('MESTRE','DOUTOR','TITULAR'))

);

CREATE TABLE DISCIPLINA (

    SIGLA CHAR(6) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    NCRED NUMBER(2) NOT NULL,
    PROF NUMBER,
    
    CONSTRAINT PK_SIGLA PRIMARY KEY(SIGLA),
    CONSTRAINT CHECK_NCRED CHECK (NCRED > 0),
    CONSTRAINT FK_PROF FOREIGN KEY(PROF) REFERENCES PROFESSOR(NFUNC) ON DELETE SET NULL

);

CREATE TABLE TURMA (
		SIGLA CHAR(6) NOT NULL,
		NUMERO NUMBER NOT NULL,
		NALUNOS NUMBER NOT NULL
		
		CONSTRAINT CK_NALUNOS CHECK(NAlunos <= 70),
		CONSTRAINT PK_TURMA PRIMARY KEY (SIGLA, NUMERO),
		CONSTRAINT FK_TURMA FOREIGN KEY (SIGLA) REFERENCES DISCIPLINA(SIGLA) ON DELETE CASCADE

);

CREATE TABLE MATRICULA (
    
    SIGLA CHAR(6) NOT NULL,
    NUMERO NUMBER NOT NULL,
    ALUNO NUMBER(8) NOT NULL,
    ANO NUMBER(4) NOT NULL,
    NOTA NUMBER(2,2),
    
    CONSTRAINT PK_MATRICULA PRIMARY KEY(SIGLA, NUMERO, ALUNO, ANO),
    CONSTRAINT FK1_MATRICULA FOREIGN KEY(SIGLA, NUMERO) REFERENCES TURMA(SIGLA, NUMERO) ON DELETE CASCADE,
    CONSTRAINT FK2_MATRICULA FOREIGN KEY(ALUNO) REFERENCES ALUNO(NUSP) ON DELETE CASCADE

);